Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code: target/lambda/release/bootstrap.zip
      Handler: main.main
      Runtime: provided
      MemorySize: 128
      Timeout: 5
      Role: !GetAtt ExecutionRole.Arn
      Environment:
        Variables:
          RUST_BACKTRACE: 1
          TOPIC_ARN: ""
          TABLE_NAME: !Ref Table

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: flavor
          AttributeType: S
      KeySchema:
        - AttributeName: flavor
          KeyType: HASH
      TableName: !Ref TableName
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  TablePolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref ExecutionRole
      PolicyName: table-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:DeleteItem
          Resource: !GetAtt Table.Arn

  # cloudwatch event
  # sns topic

Parameters:
  TableName:
    Type: String
    Description: "DynamoDB table name in which the function will store the menu"
    MinLength: 1
    MaxLength: 255
